/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Console: typeof import('./src/components/server/Console.vue')['default']
    Dashboard: typeof import('./src/components/dashboard/Dashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerCard: typeof import('./src/components/dashboard/ServerCard.vue')['default']
    TestConsoleView: typeof import('./src/view/server/TestConsoleView.vue')['default']
  }
}
