-- CreateEnum
CREATE TYPE "Permission" AS ENUM ('FILE_READ', 'FILE_WRITE', 'FILE_DELETE', 'FILE_CREATE', 'SERVER_CREATE', 'SERVER_DELETE', 'SERVER_STOP', 'SERVER_START', 'SERVER_RESTART', 'SERVER_READ', 'SERVER_UPDATE', 'SERVER_CONSOLE_READ', 'SERVER_CONSOLE_WRITE', 'NODE_CREATE', 'NODE_DELETE', 'NODE_UPDATE', 'NODE_RESTART', 'NODE_READ', 'USER_CREATE', 'USER_DELETE', 'USER_UPDATE', 'USER_READ', 'ALLOCATION_CREATE', 'ALLOCATION_DELETE', 'ALLOCATION_UPDATE', 'ALLOCATION_READ');

-- AlterTable
ALTER TABLE "User"
    ADD COLUMN "permissions" "Permission"[];
